//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingChallenge.Data.Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Circulo.
        /// </summary>
        internal static string Circulo {
            get {
                return ResourceManager.GetString("Circulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Circulos.
        /// </summary>
        internal static string Circulos {
            get {
                return ResourceManager.GetString("Circulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuadrado.
        /// </summary>
        internal static string Cuadrado {
            get {
                return ResourceManager.GetString("Cuadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuadrados.
        /// </summary>
        internal static string Cuadrados {
            get {
                return ResourceManager.GetString("Cuadrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a formas.
        /// </summary>
        internal static string Formas {
            get {
                return ResourceManager.GetString("Formas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista vacía de formas.
        /// </summary>
        internal static string FormaVacia {
            get {
                return ResourceManager.GetString("FormaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perímetro.
        /// </summary>
        internal static string Perimetro {
            get {
                return ResourceManager.GetString("Perimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes de Formas.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapecio Rectangulares.
        /// </summary>
        internal static string TrapecioRectangulo {
            get {
                return ResourceManager.GetString("TrapecioRectangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapecios Rectangulares.
        /// </summary>
        internal static string TrapeciosRectangulo {
            get {
                return ResourceManager.GetString("TrapeciosRectangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triangulos Equilateros.
        /// </summary>
        internal static string TrianguloEquilatero {
            get {
                return ResourceManager.GetString("TrianguloEquilatero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triangulos Equilateros.
        /// </summary>
        internal static string TriangulosEquilatero {
            get {
                return ResourceManager.GetString("TriangulosEquilatero", resourceCulture);
            }
        }
    }
}
